version: "3.9"

services:
  go-builder:
    build:
      context: ./docker/go-builder
    image: dev-toolchain/go-builder:1.1
    container_name: go-builder
    tty: true
  localstack:
    container_name: localstack_main
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566" # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559" # External services port range
    environment:
      - SERVICES=s3,sqs,iam,dynamodb # Specific services to enable
      - DEBUG=1 # Shows logs for easier troubleshooting
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "./volume:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  coredns:
    build:
      context: ./docker/coredns
      dockerfile: Dockerfile
    container_name: coredns
    ports:
      - "${COLIMA_IP}:53:53/udp"
      - "${COLIMA_IP}:53:53/tcp"
    volumes:
      - ./docker/coredns/Corefile:/etc/coredns/Corefile
